package com.itexpert.content.lib.enums;

public enum NotificationEnum {
    CREATION, DELETION,  DELETION_DEFINITIVELY, ARCHIVING, DEACTIVATION, ACTIVATION, REACTIVATION, DEPLOYMENT, UPDATE, REVERT, EXPORT, CREATION_OR_UPDATE, PASSWORD_CHANGE, DEPLOYMENT_VERSION, IMPORT
}
